# This is a basic workflow to help you get started with Actions

name: mirror

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  # push:
  #   branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Organization mirror
        uses: Yikun/hub-mirror-action@master
        with:
          src: github/owen10559
          dst: gitee/owen10559
          dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}
          dst_token: ${{ secrets.GITEE_TOKEN }}
          account_type: org

      - name: Black list
        uses: Yikun/hub-mirror-action@master
        with:
          src: github/owen10559
          dst: gitee/owen10559
          dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}
          dst_token: ${{ secrets.GITEE_TOKEN }}
          static_list: "mirror-test"

      - name: ssh clone style
        uses: Yikun/hub-mirror-action@master
        with:
          src: github/owen10559
          dst: gitee/owen10559
          dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}
          dst_token: ${{ secrets.GITEE_TOKEN }}
          clone_style: "ssh"

      - name: Mirror with force push (git push -f)
        uses: Yikun/hub-mirror-action@master
        with:
          src: github/owen10559
          dst: gitee/owen10559
          dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}
          dst_token: ${{ secrets.GITEE_TOKEN }}
          force_update: true
          debug: true

      - name: Mirror with force push (git push -f)
        uses: Yikun/hub-mirror-action@master
        with:
          src: github/Yikun
          dst: gitee/yikunkero
          dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}
          dst_token: ${{ secrets.GITEE_TOKEN }}
          force_update: true
          timeout: '0.5h'


