name: mirror

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:

    - name: show
      env:
        REPO_NAME: ${GITHUB_REPOSITORY#*/}
      run: echo "${env.REPO_NAME}"

    - name: show
      # run: echo "${GITHUB_REPOSITORY#owen10559/}"
      run: |
        echo $GITHUB_REPOSITORY#*/
        echo ${GITHUB_REPOSITORY#owen10559/}

    # - name: Copy Github Repos To Gitee  # 名字随便起
    #   uses: Yikun/hub-mirror-action@v1.1  # 使用Yikun/hub-mirror-action
    #   env:
    #     REPO_NAME: ${GITHUB_REPOSITORY#*/}
    #   with:
    #     src: github/owen10559  # 源端账户名(github)
    #     dst: gitee/owen10559  # 目的端账户名(gitee)
    #     dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}  # SSH密钥对中的私钥
    #     dst_token:  ${{ secrets.GITEE_TOKEN }}  # Gitee账户的私人令牌
    #     account_type: user  # 账户类型
    #     clone_style: "https"  # ssh目前无法使用
    #     debug: true  # 启用后会显示所有执行命令
    #     force_update: true  # 启用后，强制同步，即强制覆盖目的端仓库
    #     static_list: $REPO_NAME  # 获取当前仓库名称
    #     timeout: '600s'  # git超时设置，超时后会自动重试git操作